export const SET_MATCH = "SET_MATCH"
export const SET_PLAYERS = "SET_PLAYERS"
export const SET_SQUADS = "SET_SQUADS"
export const GET_SQUADS = "GET_SQUADS"
export const SET_NEW_SQUAD = "SET_NEW_SQUAD"